let alexGame = {gameName: "Spongebob vs Doodlebob", gameURL: "https://a-nunley.github.io/dev-david/", gameAuthor: "Alex Nunley"};
let nickGame = {gameName: "David V Goliath", gameURL: "(https://germannnick.github.io/Dev-David-Goliath/)", gameAuthor: "Nick Germann"};
let tuesdayGame = {gameName: "Find the Surprise!", gameURL: "https://tuesdayannb.github.io/miniature-enigma-david/", gameAuthor: "Tuesday Brown"};
let paridhiGame = {gameName: "Wow Game", gameURL: "https://pmalhotra21.github.io/wow-game/", gameAuthor: "Paridhi Malhotra"};
let kethanGame = {gameName: "Rock-Paper-Scissors", gameURL: "https://kethanpilla.github.io/dev-freddie-hw/", gameAuthor: "Kethan Pilla"};
let masonGame = { gameName: "colorName", gameURL: "https://mlsmason6.github.io/improved-computing-machine-colorName/", gameAuthor: "Mason Schrader" };
let joshuaGame = {gameName: "Escape Room", gameURL: "https://joshuabrad03.github.io/scaling-octo-david/", gameAuthor: "Joshua Bradley"};
let evanGame = {gameName: "Meh Game", gameURL: "https://mrspartan38.github.io/dev-david-hw/", gameAuthor: "Evan Sager"}
let janetGame = {gameName: "Futbol Mania", gameURL: "https://jm-2017.github.io/urban-carnival-nuExample/", gameAuthor: "Janet Martinez"};
let seanGame = {gameName: "Slides", gameURL: "https://basstbone.github.io/dev-david-hw/", gameAuthor: "Sean Oliver"};
let baileeGame = {gameName: "Escape the Garden", gameURL: "https://baileestrait.github.io/dev-david-lab/", gameAuthor: "Bailee Strait"};
let jacksonGame = {gameName: "Vroom", gameURL: "https://jaxn-harvey.github.io/dev-david/", gameAuthor: "Jackson Harvey"};
let isabellaGame = {gameName: "Catch the Butterfly", gameURL: "https://iarcher444.github.io/dev-david-lab/", gameAuthor: "Isabella Archer"};
let millyGame = {gameName: "The Emoji Game", gameURL: "https://mtrejo03.github.io/dev-david-hw/", gameAuthor: "Milly Trejo"};
let brittneyGame = {gameName: "Race Against the Clock: Dr. Cumbie's Time Tangle", gameURL: "https://bdaniel3.github.io/timeTangle/", gameAuthor: "Brittney Daniel"};
let justinGame = {gameName: "Justin's Game", gameURL: "https://justinalkire.github.io/redesigned-fiesta/", gameAuthor: "Justin Alkire"};
let allisonGame = {gameURL: "https://allisonlacy.github.io/alligamerepo/", gameAuthor: "Allison Lacy"};
let garrettGame = {gameName: "Mario Coin Catcher", gameURL: "https://gbouldin43.github.io/vigilant-giggle-david/",gameAuthor: "Garrett Bouldin"};
let spencerGame = {gameName: "Cow Game",gameURL: "https://sblakeuna.github.io/literate-octo-disco-david/",gameAuthor: "Spencer Blake"};
